services:
  web:
    container_name: "webprodsrv"
    build: app
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/var/www/html/
    networks:
      - webnet

  web-dev:
    container_name: "wevdevsrv"
    build: app
    ports: 
      - '8080:80'
    volumes:
      - ./dev:/var/www/html/
    networks:
      - devnet


networks:
  webnet: 
  devnet:
